{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{include "kepler.fullname" .}}
  namespace: {{include "kepler.namespace" .}}
  labels:
    {{- include "kepler.labels" . | nindent 4}}
  {{- with .Values.serviceMonitor.labels}}
  {{- toYaml . | nindent 4}}
  {{- end}}
  {{- with .Values.serviceMonitor.annotations}}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end}}
spec:
  selector:
    matchLabels:
      {{- include "kepler.selectorLabels" . | nindent 6}}
  endpoints:
    - port: http
      interval: {{.Values.serviceMonitor.interval}}
      path: {{.Values.serviceMonitor.path}}
{{- end}}
