apiVersion: v1
kind: ConfigMap
metadata:
  name: kepler
  namespace: kepler
  labels:
    app.kubernetes.io/name: kepler
    app.kubernetes.io/part-of: kepler
data:
  config.yaml: |
    log:
      level: debug
      format: text
    host:
      sysfs: /host/sys
      procfs: /host/proc
    monitor:
      interval: 5s
      staleness: 500ms
      maxTerminated: 100
    rapl:
      zones: []
    exporter:
      stdout:
        enabled: false
      prometheus:
        enabled: true
        debugCollectors:
          - go
    web:
      configFile: ""
    debug:
      pprof:
        enabled: false
    kube:
      enabled: false
      config: ""
      nodeName: ""
    dev:
      fake-cpu-meter:
        enabled: false
        zones: []
