apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - daemonset.yaml
  - service.yaml
  - servicemonitor.yaml
  - prometheus-rbac.yaml
  # NOTE: To enable the static sushy service uncomment the following lines
  # - redfish-secret.yaml
  # - sushy-deployment.yaml
  # - sushy-service.yaml
# NOTE: When enabling sushy-static above, also uncomment the following patch
# to enable redfish functionality with sushy-static dependency
# patches:
#   - path: patches/enable-redfish.yaml
