apiVersion: v1
kind: Secret
metadata:
  name: redfish-secret
  namespace: kepler
  labels:
    app.kubernetes.io/name: kepler
    app.kubernetes.io/part-of: kepler
type: Opaque
stringData:
  redfish.yaml: |
    # IMPORTANT: This is an experimental feature with no stability guarantees
    #
    # Example Redfish BMC Configuration for Development using Sushy tool
    #
    # Configuration structure:
    # - nodes: Maps node names/IDs to BMC identifiers
    # - bmcs: Contains connection details for each BMC

    # Node to BMC mapping
    # Key: Node identifier (Kubernetes node name, hostname, or custom ID)
    # Value: BMC identifier that references an entry in the 'bmcs' section
    nodes:
      "kind-control-plane": sushy-static # development environment
      "kind-worker": sushy-static # development environment
      "kind-worker2": sushy-static # development environment

    bmcs:
      sushy-static:
        endpoint: http://sushy-static.kepler.svc.cluster.local:8001
        username: ""
        password: ""
        insecure: true
