nodes:
  worker-node-1: bmc-1
  worker-node-2: bmc-2
bmcs:
  bmc-1:
    endpoint: http://localhost:8000
    username: admin
    password: password
    insecure: true
  bmc-2:
    endpoint: https://192.168.1.101
    username: admin
    password: secret456
    insecure: true
