name: ✨ Feature Request
description: Suggest a new feature or enhancement for Kepler
labels: [kind/feature]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Important Version Notice

        **Kepler 0.10.0 Major Rewrite:** Starting with version 0.10.0, Kepler has undergone a complete rewrite with significant architectural changes.

        - **Legacy versions (0.9.0 and earlier)** are now **frozen** - no new features will be added
        - **All new feature development** happens on the current version (0.10.0+) only
        - Feature requests for legacy versions will not be accepted

        📢 **Read more:** [CNCF Slack Announcement](https://cloud-native.slack.com/archives/C05QK3KN3HT/p1752049660866519)

  - type: dropdown
    id: version-target
    attributes:
      label: Target Version
      description: Which version should this feature be developed for?
      options:
        - Current version (0.10.0+) - New Architecture
        - Legacy version (0.9.0 or earlier) - NOT SUPPORTED
      default: 0
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature you want
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the use case?
      placeholder: Explain the problem this feature would solve
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
