log:
  level: debug # debug, info, warn, error (default: info)
  format: text # text or json (default: text)

monitor:
  #  Interval is the monitor's refresh interval. All process that
  #  have a life time (gets spawned and killed within one monitor interval)
  #  less than the interval will be ignored.
  #
  #  NOTE: setting the interval to 0s will disable the monitor refreshes
  interval: 5s

  # Staleness is the duration after the data that is computed by the monitor
  # in each refresh is considered stale and recomputed when requested again.
  #
  # This is especially useful if you have multiple prometheus instances
  # (in a HA) scrapping kepler and the data received by both instances will be
  # the same as long as the scrapes happens within the staleness duration.
  #
  # NOTE: Keep staleness shorter than the monitor interval.
  staleness: 1000ms

host:
  sysfs: /sys # Path to sysfs filesystem (default: /sys)
  procfs: /proc # Path to procfs filesystem (default: /proc)

rapl:
  zones: [] # zones to be enabled, empty enables all default zones

enable-pprof: true # Enable pprof debug endpoints

web:
  configFile: "" # Path to TLS server config file

# WARN DO NOT ENABLE THIS IN PRODUCTION - for development / testing only
dev:
  fake-cpu-meter:
    enabled: false
    zones: [] # zones to be enabled, empty enables all default zones
