scrape_configs:
  - job_name: kepler-dev
    static_configs:
      - targets: [kepler-dev:28282]

  - job_name: kepler-latest
    static_configs:
      - targets: [kepler-latest:8888]

  - job_name: host
    static_configs:
      - targets: [host.docker.internal:28282]

  - job_name: scaphandre
    fallback_scrape_protocol: PrometheusText1.0.0
    static_configs:
      - targets: [scaphandre:8080]
    scheme: http

  - job_name: node-exporter
    static_configs:
      - targets: [node-exporter:9100]

  - job_name: process-exporter
    static_configs:
      - targets: [process-exporter:9256]
