name: dev
include:
  - path:
      - ../monitoring/compose.yaml
      - ./override.yaml

services:
  ### 📦 kepler created from the current repo (local development)
  kepler-dev:
    build:
      context: ../../
      dockerfile: Dockerfile

    ports:
      # NOTE: Use 28282 for host
      - 28283:28282
    privileged: true
    volumes:
      - type: bind
        source: /proc
        target: /host/proc
        read_only: true
      - type: bind
        source: /sys
        target: /host/sys
        read_only: true
      - type: bind
        source: ./kepler-dev/etc/kepler/
        target: /etc/kepler
        read_only: true

      # NOTE: place kubeconfig here
      # e.g. cp $KUBECONFIG ./shared/kube/kubeconfig
      # for kind cluster, rename host in kubeconfig to kind-control-plane:6443
      - type: bind
        source: ./shared/kube
        target: /host/kube
        read_only: true

    command:
      - --config.file=/etc/kepler/config.yaml

    networks:
      - kepler-dev
      # - kind  # NOTE: uncomment to use kind

  kepler-old:
    image: quay.io/sustainable_computing_io/kepler:latest
    privileged: true
    pid: host
    networks:
      - kepler-old
      # - kind  # NOTE: uncomment to use kind
    cap_add:
      - ALL
    ports:
      - 29288:8888

    volumes:
      - type: bind
        source: /proc
        target: /host/proc
      - type: bind
        source: /sys
        target: /host/sys
      - type: bind
        source: ./kepler-old/etc/kepler
        target: /etc/kepler
      - type: bind
        source: ./shared/kube
        target: /host/kube
        read_only: true

    entrypoint: [/usr/bin/bash, -c]
    command:
      - |
        echo Starting kepler;
        # NOTE: uncomment to wait for estimator container
        # echo waiting for estimator socket to be ready;
        # until [[ -e /tmp/estimator.sock ]]; do
        #   echo " ... waiting for socket";
        #   sleep 1;
        # done;
        set -x;
        /usr/bin/kepler \
          -address "0.0.0.0:8888" \
          -disable-power-meter=$$DISABLE_POWER_METER \
          -v "8" \
          -enable-gpu=false \
        # -kubeconfig=/host/kube/kubeconfig

    environment:
      - DISABLE_POWER_METER=${DISABLE_POWER_METER:-false}

  scaphandre:
    image: hubblo/scaphandre
    privileged: true
    ports:
      - 28880:8080
    volumes:
      - type: bind
        source: /proc
        target: /proc
      - type: bind
        source: /sys/class/powercap
        target: /sys/class/powercap
    command: [prometheus]
    networks:
      - scaph-network

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    pid: host
    ports:
      - 29100:9100
    volumes:
      - type: bind
        source: /proc
        target: /host/proc
      - type: bind
        source: /sys
        target: /host/sys
      - type: bind
        source: /
        target: /rootfs
    command:
      # - --log.level=debug
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - --collector.disable-defaults
      - --collector.cpu
      - --collector.cpufreq
      - --collector.perf
      - --collector.perf.cpus=0-19 # specify range of all cpus
      - --collector.perf.software-profilers=ContextSwitch
      - --collector.meminfo
      - --collector.rapl
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    user: root
    cap_add: # Add capabilities for perf collection.
      - SYS_ADMIN
      - SYS_PTRACE
    networks:
      - node-exporter-network

networks:
  kepler-old:
  kepler-dev:
  scaph-network:
  node-exporter-network:
  # NOTE: uncomment to use kind
  # kind:
  #   external: true
