name: Upload Coverage to Codecov

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod

      - name: Run tests and generate coverage
        shell: bash
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          fail_ci_if_error: true
          files: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
