name: PR Checks

on:
  pull_request:
    branches: [ reboot ]

jobs:
  # docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v5.4.0
  #       with:
  #         go-version-file: go.mod
  #
  #     - name: make docs
  #       shell: bash
  #       run: |
  #         make docs && git diff --exit-code

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod

      - name: make fmt
        shell: bash
        run:  make fmt && git diff --exit-code

  codecov-upload:
    uses: ./.github/workflows/codecov-upload.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  golangci:
    permissions:
      contents: read
      pull-requests: read

    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      
      - name: setup go
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56
          args: --timeout=3m --issues-exit-code=0 ./...
          only-new-issues: true

  build-images:
    needs: [fmt, golangci, codecov-upload]
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod
          cache: false

      - name: build images for PR checks
        uses: ./.github/publish-image
        with:
          registry: "localhost:5001"
