name: Release

on: #yamllint disable-line rule:truthy
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    env:
      IMG_BASE: quay.io/sustainable_computing_io

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          # NOTE: setting fetch-depth to 0 to retrieve the entire history
          # instead of a shallow -clone so that all tags are fetched as well.
          # This is necessary for computing the VERSION using `git describe`
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod
          cache: true
          check-latest: true

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Login to Image Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMG_BASE }}
          username: ${{ secrets.BOT_NAME }}
          password: ${{ secrets.BOT_TOKEN }}

      - name: make deps
        shell: bash
        run: make deps

      - name: Build Image
        shell: bash
        run: |
          make image

      - name: Extract version
        shell: bash
        id: version
        run: |
          TAG_NAME=${{ github.ref_name }}
          echo "version=$TAG_NAME" >> "$GITHUB_OUTPUT"

      - name: Update Helm Chart Version
        shell: bash
        run: |
          VERSION=${{ steps.version.outputs.version }}
          # Remove 'v' prefix from version
          CHART_VERSION=${VERSION#v}
          # Update Chart.yaml with the release version
          sed -i "s/^version:.*/version: $CHART_VERSION/" manifests/helm/kepler/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"$VERSION\"/" manifests/helm/kepler/Chart.yaml

      - name: Package Helm Chart
        shell: bash
        run: |
          mkdir -p helm-releases
          helm package manifests/helm/kepler -d helm-releases

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: release-${{ steps.version.outputs.version }}
          generate_release_notes: true
          draft: false
          make_latest: true
          files: |
            helm-releases/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image
        shell: bash
        run: |
          make push
